// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Proto/EnumAllowingAlias.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum EnumAllowingAlias: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case eaaUnspecified // = 0
  case eaaStarted // = 1
  static let eaaRunning = eaaStarted
  case eaaFinished // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .eaaUnspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .eaaUnspecified
    case 1: self = .eaaStarted
    case 2: self = .eaaFinished
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .eaaUnspecified: return 0
    case .eaaStarted: return 1
    case .eaaFinished: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension EnumAllowingAlias: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [EnumAllowingAlias] = [
    .eaaUnspecified,
    .eaaStarted,
    .eaaFinished,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension EnumAllowingAlias: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "EAA_UNSPECIFIED"),
    1: .aliased(proto: "EAA_STARTED", aliases: ["EAA_RUNNING"]),
    2: .same(proto: "EAA_FINISHED"),
  ]
}
